export const MINIMUM_AGE_ELIGIBILITY_FOR_ACCOUNT: number = 18;
export const CONTENT_TYPE_APPLICATION_JSON: string = 'application/json';
export const CONTENT_TYPE_APPLICATION_OCTET: string = 'application/octet-stream';
export const CONTENT_TYPE_HEADER_KEY: string = 'Content-Type';
export const AUTHORIZATION_HEADER: string = 'Authorization';
export const AUTHORIZATION_BEARER: string = 'Bearer {}';
export const AUTHORIZATION_TOKEN_KEY: string = 'AUTH_TOKEN';
export const REFRESH_AUTHORIZATION_TOKEN_KEY: string = 'REFRESH_TOKEN';
export const DEFAULT_PAGE_SIZE: number = 10;
export const ANY_EMPTY: any = {};
export const AUTHENTICATION_STATUS_KEY: string = 'authenticationStatus'
export const USER_DESTINATION_PAGE_KEY: string = 'USER_STATUS_PAGE';
export const DEFAULT_UPLOAD_MAX_FILE_SIZE: number = 10; // 10 is in megabyte which is equal to 1024 * 1024 * 10;
export const X_CANCEL_REQUEST_HEADER_KEY: string = 'X-Cancel-Request';
export const DEFAULT_ERROR_MESSAGE: string = 'An error has occurred';
export const MISSING_CONFIG: string = 'Missing configuration';
