export const MINIMUM_AGE_ELIGIBILITY_FOR_ACCOUNT: number = 18;
export const CONTENT_TYPE_APPLICATION_JSON: string = 'application/json';
export const CONTENT_TYPE_HEADER_KEY: string = 'Content-Type';
export const FORM_VALIDATION_ERROR_TYPE: string = "DATA_VALIDATION";
export const AUTHORIZATION_HEADER: string = "Authorization";
export const AUTHORIZATION_BEARER: string = "Bearer {}";
export const AUTHORIZATION_TOKEN_KEY: string = "AUTH_TOKEN";
export const REFRESH_AUTHORIZATION_TOKEN_KEY: string = "REFRESH_TOKEN";
export const DEFAULT_PAGE_SIZE: number = 10;
